version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn roadmath.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-d8&7x2qv8%s2lotlq%z9_)1vyq1bm-+w--_m(o-$$jljj@tn8b2'
      - 'DJANGO_DEBUG=True'
      - 'DJANGO_SECURE_SSL_REDIRECT=False'
      - 'DJANGO_SECURE_HSTS_SECONDS=0'
      - 'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False'
      - 'DJANGO_SECURE_HSTS_PRELOAD=False'
      - 'DJANGO_SESSION_COOKIE_SECURE=False'
      - 'DATABASE_URL=postgres://postgres@db/postgres'
      - 'DJANGO_CSRF_COOKIE_SECURE=False'
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: